name: bicep-first-steps

trigger:
- none

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Visual Studio Premium met MSDN(5cae1315-6366-491f-91e3-3d8ddeb580ef)'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: 'az bicep build --file main.bicep'

    - task: PublishBuildArtifacts@1 
      displayName: 'Publish infrastructure artifact' 
      inputs: 
        PathtoPublish: '$(Build.SourcesDirectory)/main.json'  
        ArtifactName: 'main'  
        publishLocation: 'Container' 